Updated install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -22,7 +22,7 @@ else
 fi
 
 if [ ! -e "${BIN_NAME}.${BIN_EXTENSION}" ]; then
-  echo "ERROR: Missing file '${BIN_NAME}.sh'." >&2
+  echo "ERROR: Missing file '${BIN_NAME}.${BIN_EXTENSION}'." >&2
   echo "Please run this installation from within its parent directory: './install'." >&2
 
 else
